service: gateway
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:*'
          Resource: '*'

functions:
  function1:
    handler: get.handler
    events:
      - http:
          path: /
          method: post
          cors: true

  function2:
    handler: index.handler
    events:
      - http: 
          path: /post
          method: post
          cors: true
